Controllers/AdmManagementController.cs
using HelpHub.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nest;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Net.Mime;
using System.Net.NetworkInformation;
using System.Reflection;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using System.Diagnostics.Eventing.Reader;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Linq;


namespace HelpHub.Controllers
{
    public class AdmManagementController : Controller
    {


        private readonly IUSUARIODAL usuarioDAL;

        public AdmManagementController(IUSUARIODAL user)
        {

            usuarioDAL = user;
        }


        public async Task<IActionResult> Index()
        {
            IEnumerable<USUARIO> listaUSUARIOs;

            listaUSUARIOs = usuarioDAL.GetUSUARIOs().ToList();


            return await Task.Run(() => View(listaUSUARIOs));
     
        }

    }
}

Controllers/LoginController.cs
using HelpHub.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Nest;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Net.Mime;
using System.Net.NetworkInformation;
using System.Reflection;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using System.Diagnostics.Eventing.Reader;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Linq;


namespace HelpHub.Controllers
{

    public class LoginController : Controller
    {


        private readonly IUSUARIODAL usuarioDAL;
        private readonly IREQUESTRESPONSEDAL requestResponseDAL;

        public IHttpContextAccessor _httpContextAccessor;

        public LoginController(IUSUARIODAL user, IREQUESTRESPONSEDAL uArea, IHttpContextAccessor httpContextAccessor) { 

                usuarioDAL = user;
                requestResponseDAL = uArea;
                _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.Run( () => View() );

        }


        // GET: ValidaLogin
        [HttpPost]
        public async Task<IActionResult> Valida(string loginOrEmail, string senha)
        {
            IEnumerable <USUARIO> listaUSUARIOs;

            listaUSUARIOs = usuarioDAL.GetUSUARIOs();

            bool containsLoginOrEmail = false;
            bool isPasswordCorret = false;

            foreach(USUARIO user in listaUSUARIOs)
            {
                if(user.EMAIL == loginOrEmail)
                {
                    containsLoginOrEmail = true;

                    if(user.SENHA == senha)
                    {

                        @_httpContextAccessor.HttpContext.Session.SetString("SessionNome", user.NOME);
                        @_httpContextAccessor.HttpContext.Session.SetString("SessionEmail",user.EMAIL);
                        @_httpContextAccessor.HttpContext.Session.SetString("SessionID", user.ID.ToString());
                        @_httpContextAccessor.HttpContext.Session.SetString("SessionTIPO_USUARIO", user.TIPO_USUARIO.ToString());

                        isPasswordCorret = true;
                    }
                }


                if (user.EMAIL == loginOrEmail || user.NOME == loginOrEmail)
                {
                    containsLoginOrEmail = true;

                    if (user.SENHA == senha)
                    {
                        isPasswordCorret = true;
                    }
                }
            }

            if(containsLoginOrEmail && isPasswordCorret){



                IEnumerable<SOLICITACAO> listaSOLICITACOEs = new List<SOLICITACAO>();

                listaSOLICITACOEs = requestResponseDAL.GetRequests().ToList();

                return await Task.Run(() => RedirectToAction("UserArea", "UserArea"));


            }
            else
            {
                ViewBag.Message = "Usuario ou senha invalidos!";
                return await Task.Run(() => View("~/Views/Login/Index.cshtml"));
         
            }

        }

    }
}

Controllers/RegisterController.cs
using HelpHub.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Security.Cryptography;
using System.Threading.Tasks;

namespace HelpHub.Controllers
{
    public class RegisterController : Controller
    {


        private readonly IUSUARIODAL usuarioDAL;
        private readonly IREQUESTRESPONSEDAL requestRESPONSEDAL;
        public IHttpContextAccessor _httpContextAccessor;

        public RegisterController(IUSUARIODAL user, IREQUESTRESPONSEDAL rr, IHttpContextAccessor httpContextAccessor)
        {

            usuarioDAL = user;
            this.requestRESPONSEDAL = rr;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View());

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PK_USUARIO,NOME,EMAIL,SENHA,TIPO_USUARIO,DT_ULTIMO_LOGIN,QTDE_PERGUNTAS_ENV,QTDE_RESPOSTAS,CONTA_ENCERRADA,FK_ID_USUARIO_DEPARMENTO,FK_USUARIO_DEPARTAMENTO")] USUARIO user)
        {
   
            if (ModelState.IsValid)
            {


                user.FK_USUARIO_DEPARTAMENTO++;
                user.FK_ID_USUARIO_DEPARTAMENTO = user.FK_USUARIO_DEPARTAMENTO;
                user.DT_ULTIMO_LOGIN = System.DateTime.Now;
         
                usuarioDAL.AddUSUARIO(user);  
            }


            ViewBag.Message = "Cadastro realizado com sucesso!";


            IEnumerable<USUARIO> listaUSUARIOs;

            listaUSUARIOs = usuarioDAL.GetUSUARIOs();

        
            @_httpContextAccessor.HttpContext.Session.SetString("SessionNome", user.NOME);
            @_httpContextAccessor.HttpContext.Session.SetString("SessionEmail", user.EMAIL);
            @_httpContextAccessor.HttpContext.Session.SetString("SessionID",    (listaUSUARIOs.Count() + 1).ToString() );
            @_httpContextAccessor.HttpContext.Session.SetString("SessionTIPO_USUARIO", user.TIPO_USUARIO.ToString());

            IEnumerable<SOLICITACAO> listaSOLICITACOEs = new List<SOLICITACAO>();

            listaSOLICITACOEs = requestRESPONSEDAL.GetRequests().ToList();

            return await Task.Run(() => RedirectToAction("UserArea", "UserArea"));

        }
    }
}

Controllers/RequestController.cs
using HelpHub.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nest;
using System;
using System.Threading.Tasks;

namespace HelpHub.Controllers
{
    public class RequestController : Controller
    {


        private readonly ISOLICITACAODAL solicitacaoDAL;

        IHttpContextAccessor httpContextAccessor;

        public async Task<IActionResult> Index()
        {
            return await Task.Run(() => View());

        }

        public RequestController(ISOLICITACAODAL soli, IHttpContextAccessor httpContextAccessor)
        {

            solicitacaoDAL = soli;
            this.httpContextAccessor = httpContextAccessor;
        }


        public async Task<IActionResult> Create([Bind("ID,PK_SOLICITACAO,TITULO,DT_CRIACAO,PERGUNTA,DESCRICAO,QTE_CURTIDAS,FK_ID_SOLICITACAO_USUARIO,FK_SOLICITACAO_USUARIO")] SOLICITACAO soli)
        {
            if (ModelState.IsValid)
            {


                string usuario_sessao_id_str = httpContextAccessor.HttpContext.Session.GetString("SessionID");
                int usuario_sessao_id = String.IsNullOrEmpty(usuario_sessao_id_str) ? 0 : int.Parse(usuario_sessao_id_str);

                soli.FK_ID_SOLICITACAO_USUARIO = usuario_sessao_id;
                soli.FK_SOLICITACAO_USUARIO = usuario_sessao_id; 

                soli.DT_CRIACAO = System.DateTime.Now;

                solicitacaoDAL.AddSOLICITACAO(soli);
                ViewBag.Message = "Solicitacao cadastrada com sucesso!";
            }





            return await Task.Run(() => RedirectToAction("UserArea", "UserArea"));

        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HelpHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelpHub</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>


                        @if (  !String.IsNullOrEmpty(@Accessor.@HttpContext.Session.GetString("SessionID")) && !@Accessor.@HttpContext.Session.GetString("SessionID").Equals("0") )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Solicitacao</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RequestResponse" asp-action="Index">Responder Solicitacoes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserArea" asp-action="UserArea">Área de Usuário</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserArea" asp-action="Logout">Sair da Aplicação</a>
                            </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Cadastro</a>
                        </li>
                        }
                        @if (!String.IsNullOrEmpty(@Accessor.@HttpContext.Session.GetString("SessionID")) && @Accessor.@HttpContext.Session.GetString("SessionTIPO_USUARIO").Equals("1"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdmManagement" asp-action="Index">Área Administrativa</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
           @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HelpHub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>